### ISSUE TITLE
bs4.FeatureNotFound Error

### ISSUE THREAD

**Issue by Foggalong** [kenogo/spotify-lyrics-cli#2]
I get this rather nice error when running.

```python
BAD WATER - ARONCHUPA

Traceback (most recent call last):
  File "lyrics.py", line 78, in <module>
    print(get_lyrics(sys.argv[1]+' '+sys.argv[2]))
  File "lyrics.py", line 39, in get_lyrics
    soup = BeautifulSoup(lyrics_html, "lxml")
  File "/usr/local/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
(END)
```

![2018-01-20-234519_1920x1080_scrot](https://user-images.githubusercontent.com/5920259/35189116-1dc3f956-fe3c-11e7-9c73-bdc0978b745b.png)

**Comment by kenogo** [comment]
Weird... Seems like you don't have lxml for python installed (bs4 installed that for me, automatically). If you're on Debian/Ubuntu/Mint/..., install it with
```
apt install python3-lxml
```
Other distros probably also have packages. Otherwise you can still install it with
```
pip3 install lxml
```

**Comment by kenogo** [comment]
I'll add lxml to the dependencies in the README, thank you! Feel free to reopen if that didn't solve it.

**Comment by Foggalong** [comment]
Yeah, `bs4` didn't install it for me so I had to install it myself. All good now :+1:

**Comment by kenogo** [comment]
Actually, googling for some of the songs in your playlist made me realize that the script will currently probably just display you nothing or wrong lyrics even though there are lyrics on musixmatch for some of these songs. The reason is that It's just looking for any genius URL being found and does't confirm in any way that it's actually the one the user was looking for. I'll try to work on that tomorrow.
