### ISSUE TITLE
Needs to check whether genius URL might actually be the lyrics or just some other random genius URL

### ISSUE THREAD

**Issue by kenogo** [kenogo/spotify-lyrics-cli#3]
See end of #2

**Comment by Foggalong** [comment]
Can confirm. The lyrics on the left don't match [this song](https://open.spotify.com/track/0C7JhR7u07OiV7jvQPjLGJ).

![2018-01-21-000858_1920x1080_scrot](https://user-images.githubusercontent.com/5920259/35189289-4c946e8e-fe3f-11e7-8356-280b65de3953.png)

It is working for a lot of other songs though which aren't remixes. Thanks for this, I've really missed inbuilt lyrics since Spotify killed it and this can easily replace that :)

**Comment by kenogo** [comment]
Fixed :) Pull in the latest commit and enjoy! I still might add this check to musixmatch but it won't help having the actual lyrics displayed because I'm not planning on implementing yet another lyrics website as a fallback option. So it's still possible that you get the wrong lyrics displayed, but this just means they're not available on both genius and musixmatch. "Bad Water" by Aronchupa is available on musixmatch, so that displays fine now!
